package com.cdutcm.tcms.biz.model;

import java.util.Date;

public class EnLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enLog.id
     *
     * @mbggenerated Fri Mar 16 15:11:50 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enLog.visitNo
     *
     * @mbggenerated Fri Mar 16 15:11:50 CST 2018
     */
    private String visitno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enLog.ip
     *
     * @mbggenerated Fri Mar 16 15:11:50 CST 2018
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enLog.date
     *
     * @mbggenerated Fri Mar 16 15:11:50 CST 2018
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enLog.strength1
     *
     * @mbggenerated Fri Mar 16 15:11:50 CST 2018
     */
    private String strength1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enLog.strength2
     *
     * @mbggenerated Fri Mar 16 15:11:50 CST 2018
     */
    private String strength2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enLog.strength3
     *
     * @mbggenerated Fri Mar 16 15:11:50 CST 2018
     */
    private String strength3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enLog.strength4
     *
     * @mbggenerated Fri Mar 16 15:11:50 CST 2018
     */
    private String strength4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enLog.strength5
     *
     * @mbggenerated Fri Mar 16 15:11:50 CST 2018
     */
    private String strength5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enLog.strength6
     *
     * @mbggenerated Fri Mar 16 15:11:50 CST 2018
     */
    private String strength6;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enLog.freq
     *
     * @mbggenerated Fri Mar 16 15:11:50 CST 2018
     */
    private String freq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enLog.waveType
     *
     * @mbggenerated Fri Mar 16 15:11:50 CST 2018
     */
    private String wavetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enLog.schedule
     *
     * @mbggenerated Fri Mar 16 15:11:50 CST 2018
     */
    private String schedule;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enLog.id
     *
     * @return the value of enLog.id
     *
     * @mbggenerated Fri Mar 16 15:11:50 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enLog.id
     *
     * @param id the value for enLog.id
     *
     * @mbggenerated Fri Mar 16 15:11:50 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enLog.visitNo
     *
     * @return the value of enLog.visitNo
     *
     * @mbggenerated Fri Mar 16 15:11:50 CST 2018
     */
    public String getVisitno() {
        return visitno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enLog.visitNo
     *
     * @param visitno the value for enLog.visitNo
     *
     * @mbggenerated Fri Mar 16 15:11:50 CST 2018
     */
    public void setVisitno(String visitno) {
        this.visitno = visitno == null ? null : visitno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enLog.ip
     *
     * @return the value of enLog.ip
     *
     * @mbggenerated Fri Mar 16 15:11:50 CST 2018
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enLog.ip
     *
     * @param ip the value for enLog.ip
     *
     * @mbggenerated Fri Mar 16 15:11:50 CST 2018
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enLog.date
     *
     * @return the value of enLog.date
     *
     * @mbggenerated Fri Mar 16 15:11:50 CST 2018
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enLog.date
     *
     * @param date the value for enLog.date
     *
     * @mbggenerated Fri Mar 16 15:11:50 CST 2018
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enLog.strength1
     *
     * @return the value of enLog.strength1
     *
     * @mbggenerated Fri Mar 16 15:11:50 CST 2018
     */
    public String getStrength1() {
        return strength1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enLog.strength1
     *
     * @param strength1 the value for enLog.strength1
     *
     * @mbggenerated Fri Mar 16 15:11:50 CST 2018
     */
    public void setStrength1(String strength1) {
        this.strength1 = strength1 == null ? null : strength1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enLog.strength2
     *
     * @return the value of enLog.strength2
     *
     * @mbggenerated Fri Mar 16 15:11:50 CST 2018
     */
    public String getStrength2() {
        return strength2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enLog.strength2
     *
     * @param strength2 the value for enLog.strength2
     *
     * @mbggenerated Fri Mar 16 15:11:50 CST 2018
     */
    public void setStrength2(String strength2) {
        this.strength2 = strength2 == null ? null : strength2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enLog.strength3
     *
     * @return the value of enLog.strength3
     *
     * @mbggenerated Fri Mar 16 15:11:50 CST 2018
     */
    public String getStrength3() {
        return strength3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enLog.strength3
     *
     * @param strength3 the value for enLog.strength3
     *
     * @mbggenerated Fri Mar 16 15:11:50 CST 2018
     */
    public void setStrength3(String strength3) {
        this.strength3 = strength3 == null ? null : strength3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enLog.strength4
     *
     * @return the value of enLog.strength4
     *
     * @mbggenerated Fri Mar 16 15:11:50 CST 2018
     */
    public String getStrength4() {
        return strength4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enLog.strength4
     *
     * @param strength4 the value for enLog.strength4
     *
     * @mbggenerated Fri Mar 16 15:11:50 CST 2018
     */
    public void setStrength4(String strength4) {
        this.strength4 = strength4 == null ? null : strength4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enLog.strength5
     *
     * @return the value of enLog.strength5
     *
     * @mbggenerated Fri Mar 16 15:11:50 CST 2018
     */
    public String getStrength5() {
        return strength5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enLog.strength5
     *
     * @param strength5 the value for enLog.strength5
     *
     * @mbggenerated Fri Mar 16 15:11:50 CST 2018
     */
    public void setStrength5(String strength5) {
        this.strength5 = strength5 == null ? null : strength5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enLog.strength6
     *
     * @return the value of enLog.strength6
     *
     * @mbggenerated Fri Mar 16 15:11:50 CST 2018
     */
    public String getStrength6() {
        return strength6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enLog.strength6
     *
     * @param strength6 the value for enLog.strength6
     *
     * @mbggenerated Fri Mar 16 15:11:50 CST 2018
     */
    public void setStrength6(String strength6) {
        this.strength6 = strength6 == null ? null : strength6.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enLog.freq
     *
     * @return the value of enLog.freq
     *
     * @mbggenerated Fri Mar 16 15:11:50 CST 2018
     */
    public String getFreq() {
        return freq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enLog.freq
     *
     * @param freq the value for enLog.freq
     *
     * @mbggenerated Fri Mar 16 15:11:50 CST 2018
     */
    public void setFreq(String freq) {
        this.freq = freq == null ? null : freq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enLog.waveType
     *
     * @return the value of enLog.waveType
     *
     * @mbggenerated Fri Mar 16 15:11:50 CST 2018
     */
    public String getWavetype() {
        return wavetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enLog.waveType
     *
     * @param wavetype the value for enLog.waveType
     *
     * @mbggenerated Fri Mar 16 15:11:50 CST 2018
     */
    public void setWavetype(String wavetype) {
        this.wavetype = wavetype == null ? null : wavetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enLog.schedule
     *
     * @return the value of enLog.schedule
     *
     * @mbggenerated Fri Mar 16 15:11:50 CST 2018
     */
    public String getSchedule() {
        return schedule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enLog.schedule
     *
     * @param schedule the value for enLog.schedule
     *
     * @mbggenerated Fri Mar 16 15:11:50 CST 2018
     */
    public void setSchedule(String schedule) {
        this.schedule = schedule == null ? null : schedule.trim();
    }
}