package com.cdutcm.tcms.biz.model;

import java.util.Date;
import java.util.List;

import com.cdutcm.core.util.JsonIDSerializer;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

public class ExecRecipel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exec_recipel.id
     *
     * @mbggenerated Fri Mar 02 15:16:07 CST 2018
     */
	@JsonSerialize(using = JsonIDSerializer.class)
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exec_recipel.recipel_id
     *
     * @mbggenerated Fri Mar 02 15:16:07 CST 2018
     */
	@JsonSerialize(using = JsonIDSerializer.class)
    private Long recipelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exec_recipel.recipel_item_id
     *
     * @mbggenerated Fri Mar 02 15:16:07 CST 2018
     */
	@JsonSerialize(using = JsonIDSerializer.class)
    private Long recipelItemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exec_recipel.xwname
     *
     * @mbggenerated Fri Mar 02 15:16:07 CST 2018
     */
    private String xwname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exec_recipel.starttime
     *
     * @mbggenerated Fri Mar 02 15:16:07 CST 2018
     */
    private Date starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exec_recipel.endtime
     *
     * @mbggenerated Fri Mar 02 15:16:07 CST 2018
     */
    private Date endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exec_recipel.zxys_id
     *
     * @mbggenerated Fri Mar 02 15:16:07 CST 2018
     */
    private Long zxysId;
    
    
    private String status;
    
    private List<ExecRecipelItem> execRecipelItem;
    
    

    public List<ExecRecipelItem> getExecRecipelItem() {
		return execRecipelItem;
	}

	public void setExecRecipelItem(List<ExecRecipelItem> execRecipelItem) {
		this.execRecipelItem = execRecipelItem;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exec_recipel.id
     *
     * @return the value of exec_recipel.id
     *
     * @mbggenerated Fri Mar 02 15:16:07 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exec_recipel.id
     *
     * @param id the value for exec_recipel.id
     *
     * @mbggenerated Fri Mar 02 15:16:07 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exec_recipel.recipel_id
     *
     * @return the value of exec_recipel.recipel_id
     *
     * @mbggenerated Fri Mar 02 15:16:07 CST 2018
     */
    public Long getRecipelId() {
        return recipelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exec_recipel.recipel_id
     *
     * @param recipelId the value for exec_recipel.recipel_id
     *
     * @mbggenerated Fri Mar 02 15:16:07 CST 2018
     */
    public void setRecipelId(Long recipelId) {
        this.recipelId = recipelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exec_recipel.recipel_item_id
     *
     * @return the value of exec_recipel.recipel_item_id
     *
     * @mbggenerated Fri Mar 02 15:16:07 CST 2018
     */
    public Long getRecipelItemId() {
        return recipelItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exec_recipel.recipel_item_id
     *
     * @param recipelItemId the value for exec_recipel.recipel_item_id
     *
     * @mbggenerated Fri Mar 02 15:16:07 CST 2018
     */
    public void setRecipelItemId(Long recipelItemId) {
        this.recipelItemId = recipelItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exec_recipel.xwname
     *
     * @return the value of exec_recipel.xwname
     *
     * @mbggenerated Fri Mar 02 15:16:07 CST 2018
     */
    public String getXwname() {
        return xwname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exec_recipel.xwname
     *
     * @param xwname the value for exec_recipel.xwname
     *
     * @mbggenerated Fri Mar 02 15:16:07 CST 2018
     */
    public void setXwname(String xwname) {
        this.xwname = xwname == null ? null : xwname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exec_recipel.starttime
     *
     * @return the value of exec_recipel.starttime
     *
     * @mbggenerated Fri Mar 02 15:16:07 CST 2018
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exec_recipel.starttime
     *
     * @param starttime the value for exec_recipel.starttime
     *
     * @mbggenerated Fri Mar 02 15:16:07 CST 2018
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exec_recipel.endtime
     *
     * @return the value of exec_recipel.endtime
     *
     * @mbggenerated Fri Mar 02 15:16:07 CST 2018
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exec_recipel.endtime
     *
     * @param endtime the value for exec_recipel.endtime
     *
     * @mbggenerated Fri Mar 02 15:16:07 CST 2018
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exec_recipel.zxys_id
     *
     * @return the value of exec_recipel.zxys_id
     *
     * @mbggenerated Fri Mar 02 15:16:07 CST 2018
     */
    public Long getZxysId() {
        return zxysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exec_recipel.zxys_id
     *
     * @param zxysId the value for exec_recipel.zxys_id
     *
     * @mbggenerated Fri Mar 02 15:16:07 CST 2018
     */
    public void setZxysId(Long zxysId) {
        this.zxysId = zxysId;
    }
}